### ISSUE TITLE
`ts-reaktive-marshal-akka` didn't survive Bintraygeddon

### ISSUE THREAD

**Issue by ennru** [2m/authors#213]
Looks like the `ts-reaktive-marshal-akka` didn't find its way out of Bintray before it disappeared.

**Comment by 2m** [comment]
Yup. That was a nice streaming JSON parser. Will try to replace it with [Alpakka JSON](https://doc.akka.io/docs/alpakka/current/data-transformations/json.html) and https://github.com/mdedetrich/akka-streams-json.

**Comment by 2m** [comment]
1.3 has just been released that does not use `ts-reaktive-marshal-akka` anymore.

**Comment by ennru** [comment]
Thank you.
