### ISSUE TITLE
Issues locating `scmInfo` value

### ISSUE THREAD

**Issue by seglo** [2m/authors#80]
Hi @2m ! :wave:,

I'm trying to use `sbt-authors` to release Alpakka Kafka and I ran into an issue where the `scmInfo` setting could not be found because it was not in `ThisBuild` scope (if I added it to that scope, everything works).  I noticed you have a commit that resolves this issue (https://github.com/2m/authors/commit/f051c361ee7cbba7ccf747a328bf5d75c9da7b25), but I could only find this incremental 1.0.2 release for it on maven central: https://search.maven.org/artifact/lt.dvim.authors/authors-core_2.12/1.0.2%2B48-84cf9af9/jar

Do you plan to release a 1.0.3 soon?

**Comment by 2m** [comment]
Hi. Good to hear from you! I'll try to release it as soon as possible.

**Comment by 2m** [comment]
Released 1.1: https://github.com/2m/authors/releases/tag/v1.1

**Comment by seglo** [comment]
Thanks @2m
