### ISSUE TITLE
sbt authors will clear clipboard

### ISSUE THREAD

**Issue by seglo** [2m/authors#81]
On my machine, when I run the `authors` task my clipboard will be cleared instead of containing the author markdown data.  I'm not sure why this occurs, because when I run the `java.awt` clipboard management code you have in an SBT Scala console it works as expected (https://github.com/2m/authors/blob/master/plugin/src/main/scala/AuthorsPlugin.scala#L44..L48).  

The issue appears the same as the one reported by some users on this SO post (https://stackoverflow.com/questions/3591945/copying-to-the-clipboard-in-java/3592022#comment98033765_3592022).

Working around it by just using `authorsFile`, though maybe `authors` could just dump to stdout instead?

**Comment by 2m** [comment]
I have created #82 which switches `authors` task to print to stdout instead. It also adds `authorsClipboard` which puts the summary to the clipboard. I'll close this ticket, as it seems there is no discovered way of how to make the clipboard functionality more reliable.
